export enum WalletStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  BLOCKED = 'BLOCKED',
  CLOSED = 'CLOSED',
  UNDER_REVIEW = 'UNDER_REVIEW',
}

export enum WalletTransactionType {
  REWARD = 'REWARD',
  RELEASE = 'RELEASE',
  WITHDRAW = 'WITHDRAW',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum WalletTransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum WithdrawalStatus {
  OTP_PENDING = 'OTP_PENDING',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  PROCESSING = 'PROCESSING',
  PAID = 'PAID',
  FAILED = 'FAILED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  SECURITY_REVIEW_REQUIRED = 'SECURITY_REVIEW_REQUIRED',
  OTP_EXPIRED = 'OTP_EXPIRED',
}

export enum WithdrawalSecurityStatus {
  NORMAL = 'NORMAL',
  OTP_LOCKED = 'OTP_LOCKED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  UNLOCKED = 'UNLOCKED',
}

export enum PaymentMethod {
  MOBILE_MONEY = 'MOBILE_MONEY',
}

export enum MobileMoneyProvider {
  MTN_MOMO = 'MTN_MOMO',
  MOOV_MONEY = 'MOOV_MONEY',
  CELTIIS_CASH = 'CELTIIS_CASH',
}

export enum PaymentExecutionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum PaymentBatchStatus {
  DRAFT = 'DRAFT',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum FeeType {
  FIXED = 'FIXED',
  PERCENTAGE = 'PERCENTAGE',
}

export enum PaymentNotificationType {
  WALLET_CREDITED = 'WALLET_CREDITED',
  WITHDRAWAL_OTP_SENT = 'WITHDRAWAL_OTP_SENT',
  WITHDRAWAL_OTP_RESENT = 'WITHDRAWAL_OTP_RESENT',
  WITHDRAWAL_OTP_DELIVERED = 'WITHDRAWAL_OTP_DELIVERED',
  WITHDRAWAL_OTP_UNDELIVERED = 'WITHDRAWAL_OTP_UNDELIVERED',
  WITHDRAWAL_OTP_DELIVERY_UNKNOWN = 'WITHDRAWAL_OTP_DELIVERY_UNKNOWN',
  WITHDRAWAL_OTP_LOCKED = 'WITHDRAWAL_OTP_LOCKED',
  WITHDRAWAL_OTP_UNLOCKED = 'WITHDRAWAL_OTP_UNLOCKED',
  WITHDRAWAL_REQUESTED = 'WITHDRAWAL_REQUESTED',
  WITHDRAWAL_APPROVED = 'WITHDRAWAL_APPROVED',
  WITHDRAWAL_REJECTED = 'WITHDRAWAL_REJECTED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  ADMIN_WITHDRAWAL_ALERT = 'ADMIN_WITHDRAWAL_ALERT',
}

export enum OtpProvider {
  CONSOLE = 'console',
  INFOBIP = 'infobip',
}

export enum OtpDeliveryStatus {
  NOT_REQUIRED = 'NOT_REQUIRED',
  CREATED = 'CREATED',
  SENT_TO_PROVIDER = 'SENT_TO_PROVIDER',
  DELIVERED = 'DELIVERED',
  UNDELIVERED = 'UNDELIVERED',
  FAILED = 'FAILED',
  DELIVERY_UNKNOWN = 'DELIVERY_UNKNOWN',
  DELIVERY_TIMEOUT = 'DELIVERY_TIMEOUT',
}
